### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by DeleteThisAcount** [towerofnix/bantisocial#314]
it dont work

**Comment by joker314** [comment]
Hi! Thank you for contributing to this project by sending us bug reports. It'd be really lovely if you could give more information -- so contributors can resolve the issue in a more speedy manner -- and, to prevent excess work from contributors. It's not as helpful to file two-word issues.

Do you mean that the linked site in the repository's description (https://meta.decent.chat) is returning a 502 error? If so, that's expected behaviour -- the site is intermittently shut down.

Do you mean that you tried to run the code provided in the repository and it didn't work? If so, could you provide details about any error messages you saw, or whether you received certain response codes to requests but they weren't 200 codes?

Thanks again for reporting this!

**Comment by towerofnix** [comment]
@joker314 Right, thanks for that post. @DeleteThisAcount do read it!

For what it's relevant, development on decent is effectively halted. You may try to get it running, and it will probably work, and I will be happy to help you figure out how to get it to work, but there are no guarantees.

Like @joker314 said, meta.decent.chat is down. If you're interested in running decent on your own computer, you'd best start [here](https://github.com/decent-chat/decent#installation).

**Comment by DeleteThisAcount** [comment]
ok.

I was wondering why the website don't work
