### ISSUE TITLE
Rename to something better than bantisocial

### ISSUE THREAD

**Issue by heyitsmeuralex** [towerofnix/bantisocial#78]
![image](https://user-images.githubusercontent.com/9429556/33812614-8b8effc6-de16-11e7-8ccf-88dcc7a76dc1.png)
plus a bunch of people saying "I" :taco:

**Comment by eq** [comment]
Haha yes

**Comment by TheInitializer** [comment]
https://en.wikipedia.org/wiki/Banshee_(media_player)

**Comment by towerofnix** [comment]
^ Yup, definitely note this. Banshee-the-media-player has been around since 2005 - probably best to not take its name!

**Comment by TheInitializer** [comment]
still don't really see what was wrong with the original name - `antisocial.chat`

**Comment by towerofnix** [comment]
I'd rather make it not have "antisocial" in the name. I'm reminded of how Discord has meme jokes in the loading screen which are *fun* but not at all professional, which tends to make people frown and generally dislike using it (even though it's generally a fine chat service).

**Comment by TheInitializer** [comment]
>Discord has meme jokes in the loading screen

oh yeah. can we not do that, please? 📦 
I much prefer how Slack has inspirational messages instead, and lets you add your own.

That said, with professionalism in mind, ":b:antisocial" definitely has the wrong effect.

**Comment by PullJosh** [comment]
If we want a name that's actually professional, it would be cool to have it's name reference the fact that the entire thing is decentralized.

Maybe some sort of oxymoron about it being a decentralized forum?

**Comment by heyitsmeuralex** [comment]
_Decent_, because it's decent and also `decent`ralized

**Comment by towerofnix** [comment]
Decent isn't used *anywhere* as far as I can tell (nothing on wikipedia or first couple pages of google-searching). That's a +1 :package:

**Comment by eq** [comment]
decent: it's ok i guess™

**Comment by PullJosh** [comment]
We could make some killer homepage copy out of this:

### Decent is the decentralized chat system that's absolutely okay

#### Decentralized 
Rather than living on a central server<sup>[1]</sup>, Decent runs on servers by and for the people. You never have to give a single corporate identity the power to control the way you speak. Instead, connect to servers that are created by the users. Nobody has access to *every* server, so nobody has the power to tear down a system you rely on.

#### Tolerable to Use
Since Decent doesn't harvest your data like other chat systems<sup>[2]</sup>, we don't have a ton of cash to spend doing research or hiring professionals. But after hours of careful consideration, we've made all sorts of uninformed decisions that we think will improve your experience.

Decent works hard to give as much power as possible to the user. With unlimited custom emotes, unlimited pinned messages, and lots of markdown features in messages, decent is sure to meet most of your expectations. The default client has a moderately nice looking UI, a sufficient supply of keyboard shortcuts, and plenty of other nearly-noteworthy features, making it the perfect fit for someone who wants to send decentralized messages without a substantial hassle.

#### Open Source
Paranoid? So is [Mark Zuckerberg](https://www.theguardian.com/technology/2016/jun/22/mark-zuckerberg-tape-webcam-microphone-facebook)<sup>[3]</sup>. If you don't trust us<sup>[4]</sup>, you can view the source code for *everything*. Although our code isn't perfect<sup>[5]</sup>, it's worth a read. Take a poke around at the server-side code or your client of choice, and make sure nobody's snooping.

There are other benefits to be had from an open-source program as well. If there's something that's bothering you about Decent, you have the power to fix it! Write up some new code and give us a shout, and we'll consider your changes.

#### 110% Hipster
With just dozens of users around the globe, Decent is a hidden gem. You won't find every redditor and their mother around these parts, nor will you find all your coworkers. In fact, unless you specifically direct someone to Decent, they probably won't be here at all! Think of the freedom!

Plus, when you *do* convert someone to the marginally improved world of decentralized and demonetized messaging, they'll like you just a little bit better. You're *cool* now.<sup>[6]</sup>

---
<sup>[1]</sup> We can't afford that...
<sup>[2]</sup> [Not pointing any fingers.](https://discordapp.com/)
<sup>[3]</sup> Mark knows *exactly* how much information Facebook collects.
<sup>[4]</sup> Good call.
<sup>[5]</sup> Some would call it "decent"
<sup>[6]</sup> Ha ha just kidding.

**Comment by PullJosh** [comment]
For real though: Is everyone content with renaming to Decent? Personally, I think it's brilliant.

**Comment by towerofnix** [comment]
Yes :tada:
